### ISSUE TITLE
Some question about GSDM validation implementation

### ISSUE THREAD

**Issue by cctgem** [moliusimon/csdm#3]
Hi,
I'm confused about the GSDM test stage because of unknown ground truth. The origin method is proposed to address video so prediction of the previous frame is used to approximate the ground truth.But I don't know how to work on the data set like the LFPW and the exception "args['target'][mapping, ...] - params, rotations, center=False KeyError: 'target'" is thrown in your implementation.

I would like to know if I have done something wrong and thanks for this wonderful library!

**Comment by moliusimon** [comment]
Hello cctgem,

In the case of GSDM, we adapted the method to the static case (it is straight-forward).

Originally GSDM applies PCA both to the feature vectors and the delta-x taking into account the last frame fitting. Then it extracts the first principal component of delta-x and two from the feature vectors to define the sub-space and split it into octants. For our implementation we extract all the components (by default also 3) from the feature PCs, thus working with static frames instead of sequences.

About the error, could you please paste the traceback? Thanks.

**Comment by cctgem** [comment]
Hello,
Thank you for the explanation. The exception information in as follow:

Traceback (most recent call last):
  File "D:\Program Files (x86)\JetBrains\PyCharm Community Edition 2016.3\helpers\pydev\pydevd.py", line 1596, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "D:\Program Files (x86)\JetBrains\PyCharm Community Edition 2016.3\helpers\pydev\pydevd.py", line 974, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "F:/face/csdm/main_gsdm_300w.py", line 76, in <module>
    validate_model(path+model_file, path+results_file, data['test'])
  File "F:/face/csdm/main_gsdm_300w.py", line 55, in validate_model
    predictions = model.align(data['images'], num_steps=steps, save_all=True)
  File "F:/face/csdm\cascaded\cascade\cascade.py", line 107, in align
    params = f_align(images, params[0], mapping, i, args=args)
  File "F:/face/csdm\cascaded\cascade\gsdm_rotate.py", line 88, in _align_step
    args['target'][mapping, ...] - params, rotations, center=False
KeyError: 'target'

I guess the "args" must be filled outside the align function.To my knowledge, GSDM computes delta-x to determine sub-space which samples fall into,both in train and align step.But in align step, the delta-x is unknown. According the origin paper"In testing delta-x is unknown and assuming that the movement between two consecutive frames is small the prediction of the previous frame is used to approximate delta-x", I think the "args["target"]" in your code is ground truth shape. I'm not sure whether my understanding is correct.

Look forward to your reply.
